CREATE TABLE IF NOT EXISTS console_users (
    id            VARCHAR(36)  NOT NULL PRIMARY KEY,
    email         VARCHAR(256) NOT NULL UNIQUE,
    name          VARCHAR(128),
    password_hash VARCHAR(256) NOT NULL,
    created_at    DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at    DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
