name: applad
description: Official Dart SDK for Applad — client-side (Dio) and server-side (http) in one package.
version: 0.2.0
homepage: https://github.com/mittolabs/applad

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  dio: ^5.4.3
  http: ^1.2.0
  web_socket_channel: ^3.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.0
