import 'dart:io';
import 'package:args/command_runner.dart';
import 'package:applad_core/applad_core.dart';
import 'package:path/path.dart' as p;
import '../utils/output.dart';
import '../utils/config_finder.dart';

/// Manages environment variables and .env.example generation.
final class EnvCommand extends Command<void> {
  EnvCommand() {
    addSubcommand(EnvGenerateCommand());
    addSubcommand(EnvValidateCommand());
  }

  @override
  String get name => 'env';

  @override
  String get description => 'Manages environment variables and extraction.';
}

/// Scans config for ${VAR} and updates .env.example.
final class EnvGenerateCommand extends Command<void> {
  EnvGenerateCommand() {
    argParser.addOption(
      'path',
      abbr: 'p',
      help: 'Path to the root config directory (default: auto-discover).',
    );
  }

  @override
  String get name => 'generate';

  @override
  String get description =>
      'Scans config for \${VAR} and updates .env.example.';

  @override
  Future<void> run() async {
    final configPath = argResults!['path'] as String?;
    final finder = const ConfigFinder();
    final String rootPath;

    try {
      rootPath = configPath ?? finder.requireRoot();
    } catch (e) {
      Output.error(e.toString());
      return;
    }

    Output.info('Scanning config for \${VAR} references in $rootPath...');

    const extractor = VVarExtractor();
    final vars = extractor.extractFromPath(rootPath);

    if (vars.isEmpty) {
      Output.info('No \${VAR} references found.');
      return;
    }

    final exampleFile = File(p.join(rootPath, '.env.example'));
    final buffer = StringBuffer();
    buffer.writeln('# Auto-generated by applad env generate');
    buffer.writeln('# Scanned at: ${DateTime.now().toIso8601String()}');
    buffer.writeln();

    for (final v in vars.toList()..sort()) {
      buffer.writeln('$v=');
    }

    exampleFile.writeAsStringSync(buffer.toString());
    Output.success('Generated .env.example with ${vars.length} variables.');
  }
}

/// Ensures all required vars are set in the current environment or .env.
final class EnvValidateCommand extends Command<void> {
  EnvValidateCommand() {
    argParser.addOption(
      'path',
      abbr: 'p',
      help: 'Path to the root config directory (default: auto-discover).',
    );
  }

  @override
  String get name => 'validate';

  @override
  String get description => 'Ensures all required vars are set.';

  @override
  Future<void> run() async {
    final configPath = argResults!['path'] as String?;
    final finder = const ConfigFinder();
    final String rootPath;

    try {
      rootPath = configPath ?? finder.requireRoot();
    } catch (e) {
      Output.error(e.toString());
      return;
    }

    const extractor = VVarExtractor();
    final requiredVars = extractor.extractFromPath(rootPath);

    if (requiredVars.isEmpty) {
      Output.success('No \${VAR} references found. Validation passed.');
      return;
    }

    final missing = <String>[];
    for (final v in requiredVars) {
      if (!Platform.environment.containsKey(v)) {
        // Also check .env if it exists
        final envFile = File(p.join(rootPath, '.env'));
        if (envFile.existsSync()) {
          final content = envFile.readAsStringSync();
          if (!content.contains(RegExp('$v='))) {
            missing.add(v);
          }
        } else {
          missing.add(v);
        }
      }
    }

    if (missing.isNotEmpty) {
      Output.error('Missing required environment variables:');
      for (final m in missing) {
        Output.info('  - $m');
      }
      exitCode = 1;
    } else {
      Output.success('All required variables are present.');
    }
  }
}
